input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "environment" => "dev"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "document-transfer-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}